### ISSUE TITLE
Repeated trader refreshes can open a closed market

### ISSUE THREAD

**Issue by ywhcuhk** [flexemarkets/fm-issues#10]
In a closed marketplace, if I refresh the browser multiple times, I will get into the page where I can submit orders. I got two screenshots, one is when the market is showing closed:

![1](https://user-images.githubusercontent.com/4349929/29726314-3d744116-899d-11e7-82c0-c6147d1c0ce3.png)

and the other is when I refresh browser multiple times and got into the market and submitted a sell order:

![2](https://user-images.githubusercontent.com/4349929/29726326-409f3634-899d-11e7-9129-817979e63b6b.png)

**Comment by JanStureNielsen** [comment]
I reproduced this on Heroku in the dev account with `test0` -- after repeated refreshed in a closed marketplace, the marketplace is opened. The good news it that the improved performance development branch is not susceptible to this bug so this bug won't be reproducible after these performance enhancements are completed next week. I'll keep this open until that's deployed.

**Comment by JanStureNielsen** [comment]
This is no longer possible.
