### ISSUE TITLE
Management of a marketplace (e.g. 159) from different accounts

### ISSUE THREAD

**Issue by nitramiz** [flexemarkets/fm-issues#12]
Dylan and I were playing around with our own SSW bots in our own separate accounts, but we were both having issues with starting/pausing our individual markets. I realized that I was in the wrong marketplace (Dylan's market's id of 159, rather than mine 153), but I was logged in with the dev account and I was trying to start/pause "my" market, thinking that it was my account's market and he was doing the same, which lead to pausing/closing the same market simultaneously.
I exported the marketplace.csv to see what's in it and under the account column was Dylan's account (tuneful-devisee), not mine (dev). I was able to manage Dylan's market, that I have not created, and interact with it - play/pause, export csv. 
So, it seems like all marketplaces are accessible by all "manager" accounts, which I was able to test by changing the marketplace id in the URL from my dev account. It worked from Dylan's account as well - he could play, pause, export others' markets. 
The Marketplaces page is showing the correct marketplaces for a particular account (meaning - the ones created by that account), but if you send a request to another marketplace that's not on the list by manually changing the id in the URL, you can manage it.

**Comment by JanStureNielsen** [comment]
This is not/no-longer possible.
