### ISSUE TITLE
Test accounts can view marketplaces they're not a part of

### ISSUE THREAD

**Issue by nitramiz** [flexemarkets/fm-issues#13]
Test accounts can go to every single marketplace, even if they've not been added as traders to the marketplace while it was being created. The test accounts that were not added initially can just view the market, but they don't have any cash/units. 
This can be replicated by changing the marketplace id again in the URL from a test account.
Tested by viewing Dylan's market (159) with a test33 account, which was not included in his market. He had only added 1-18 test accounts.

**Comment by JanStureNielsen** [comment]
This was fixed a long time ago.
