### ISSUE TITLE
FM-UI shows incorrectly shows an open marketplace as closed.

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#14]
The web ui shows a marketplace as closed when it is actually open (can see the session is open and send orders through fm-shell). Sometimes on refreshing the page the marketplace is correctly reloaded. Tested with clearing history, cache and restarting the browser.

![screen shot 2018-01-05 at 14 48 33](https://user-images.githubusercontent.com/2361597/34594858-aff53036-f227-11e7-9444-dc1c065d4051.png)
![screen shot 2018-01-05 at 14 48 41](https://user-images.githubusercontent.com/2361597/34594862-b22380e2-f227-11e7-8d5f-e8eec8abaf44.png)

Console log shows this:
```
Opening Web Socket...  
Web Socket Opened...  
>>> CONNECT
authorization:Bearer eyJhbGciOiJIUzUxMiJ9.eyJwcmluY2lwYWwiOiJqb2N1bmQtYnVkZHl8bnlhZGF2dW5pbWVsYkBnbWFpbC5jb20iLCJleHAiOjE1MTU5ODg4MTEsImF1dGhvcml0aWVzIjpbeyJhdXRob3JpdHkiOiJST0xFX01BTkFHRVIifSx7ImF1dGhvcml0eSI6IlJPTEVfVVNFUiJ9XSwiYWNjb3VudCI6ImpvY3VuZC1idWRkeSIsImVtYWlsIjoibnlhZGF2dW5pbWVsYkBnbWFpbC5jb20ifQ.VUFE8Gzu2dwYrcDyYvqbtNjoaLvRoEmtk7eb3Wq3zo9MX7VfN-_KtFdOFz6zrZ5ngfZNiVqKJtyEfY_wvYGdlg
accept-version:1.2,1.1,1.0
heart-beat:30000,30000

<<< CONNECTED
version:1.2
heart-beat:30000,30000
user-name:jocund-buddy|nyadavunimelb@gmail.com

connected to server undefined 
send PING every 30000ms  
check PONG every 30000ms  
>>> SUBSCRIBE
id:sub-0
destination:/topic/marketplaces/165

>>> SUBSCRIBE
id:sub-1
destination:/app/marketplaces/165

>>> SUBSCRIBE
id:sub-2
destination:/user/queue/marketplaces/165

>>> PING
<<< PONG
>>> PING
<<< PONG
```

**Comment by JanStureNielsen** [comment]
This was fixed a long time ago.
