### ISSUE TITLE
AdHoc Markets: Internal Server Error on fetching Current Session and Current Holding 

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#15]
Created a new marketplace with 2 markets. Then used following API endpoints, both resulting in same error, irrespective of whether using a web browser or Python client.

```
https://fm-data.herokuapp.com/api/marketplaces/304/currentSession
https://fm-data.herokuapp.com/api/marketplaces/304/currentHolding
```

Error:
```
{
  "status" : "INTERNAL_SERVER_ERROR",
  "error" : "SERVER_ERROR",
  "message" : "Snap! :o"
}
```

Response Headers:
```
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Type: application/hal+json;charset=UTF-8
Date: Mon, 16 Jul 2018 05:04:40 GMT
Expires: 0
Pragma: no-cache
Server: Cowboy
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Transfer-Encoding: chunked
Via: 1.1 vegur
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
```

**Comment by darkfishy** [comment]
Also, the marketplace is entirely new and no sessions were started. `https://fm-data.herokuapp.com/api/marketplaces/304/sessions` will give an empty `sessions` list.

**Comment by darkfishy** [comment]
List of endpoints with related error, likely due to empty session and/or market/orderbook.
- https://fm-data.herokuapp.com/api/markets/590/private-traders
- https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId=590
- https://fm-data.herokuapp.com/api/orders/search/orders-completed?marketId=590
- https://fm-data.herokuapp.com/api/orders-json/orders-available?marketId=590
- https://fm-data.herokuapp.com/api/orders-json/orders-completed?marketId=590

**Comment by nitinef** [comment]
These may happen when the MP is created but not opened for the first time? I think there is some initialization that takes place when an MP is first opened.

**Comment by JanStureNielsen** [comment]
These mis-handlings in the API ow return an error:
```
{
  "status" : "BAD_REQUEST",
  "error" : "SESSION_INVALID",
  "message" : "Invalid session."
}
```

except for the `marketplace/{id}/sessions` API which returns an empty list.
