### ISSUE TITLE
Incorrect naming in Import/Export holdings Dialog box

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#17]
The dialog box should state Import/Export holdings instead of Import/Export Marketplace.

<img width="551" alt="mp_1" src="https://user-images.githubusercontent.com/2361597/42851507-682f6136-8a70-11e8-9335-cfbfab4035ae.png">
<img width="300" alt="mp_2" src="https://user-images.githubusercontent.com/2361597/42851511-6d2dd7d0-8a70-11e8-9b36-8a05d91e52d0.png">

**Comment by JanStureNielsen** [comment]
Closed in https://github.com/flexemarkets/fm-ui/commit/33ab6ea92b8063686961f592c9a593451f660f66
