### ISSUE TITLE
API error on marketplace close/pause

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#18]
The marketplace effect is correct (i.e., it closes and pauses) but the API response is an Internal Server Error. CURL output below:

$ ./patch --data-binary @patch-closed.json $FMAPI_HOME/sessions/6077
*   Trying 52.7.153.92...
* TCP_NODELAY set
* Connected to fm-data.herokuapp.com (52.7.153.92) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /opt/local/share/curl/curl-ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Heroku, Inc.; CN=*.herokuapp.com
*  start date: Apr 19 00:00:00 2017 GMT
*  expire date: Jun 22 12:00:00 2020 GMT
*  subjectAltName: host "fm-data.herokuapp.com" matched cert's "*.herokuapp.com"
*  issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
*  SSL certificate verify ok.
* Server auth using Basic with user 'still-procto|nitin.yadav@unimelb.edu.au'
> PATCH /api/sessions/6077 HTTP/1.1
> Host: fm-data.herokuapp.com
> Authorization: Basic c3RpbGwtcHJvY3RvfG5pdGluLnlhZGF2QHVuaW1lbGIuZWR1LmF1OnIyZDJ3ZTI=
> User-Agent: curl/7.61.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 66
>
* upload completely sent off: 66 out of 66 bytes
< HTTP/1.1 500
< Server: Cowboy
< Connection: keep-alive
< Set-Cookie: JSESSIONID=48613726C83813345275E4A708C4B86E; Path=/; Secure; HttpOnly
< X-Content-Type-Options: nosniff
< X-Xss-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< Strict-Transport-Security: max-age=31536000 ; includeSubDomains
< X-Frame-Options: DENY
< Content-Type: application/hal+json;charset=UTF-8
< Transfer-Encoding: chunked
< Date: Thu, 19 Jul 2018 06:07:57 GMT
< Via: 1.1 vegur
<
{
  "status" : "INTERNAL_SERVER_ERROR",
  "error" : "SERVER_ERROR",
  "message" : "Snap! :o"
* Connection #0 to host fm-data.herokuapp.com left intact
}

**Comment by JanStureNielsen** [comment]
This is now fixed.
