### ISSUE TITLE
Incorrect sorting of BID and ASK orders in UI and Incorrect Spread

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#19]
The BUY orders should be sorted in descending order (top to bottom) and the SELL orders in ascending order (bottom to top). The spread should be the difference between the best bid and the best ask.
![incorrectspread](https://user-images.githubusercontent.com/2361597/43051521-9a3d6758-8e5e-11e8-88ba-676f9feac10d.png)

**Comment by JanStureNielsen** [comment]
This is now fixed and deployed.
