### ISSUE TITLE
Incorrect number of units after a trade

### ISSUE THREAD

**Issue by nitramiz** [flexemarkets/fm-issues#2]
On the right-hand side (under All/Mine), the number of completed order units is incorrect. After one trade, with one stock - Units says 2. Same in all views - dev, test1 and test2.
The two should be a one.
![image](https://cloud.githubusercontent.com/assets/16788093/26404042/370917ae-4099-11e7-93cf-3ff39c1a7d54.png)

**Comment by JanStureNielsen** [comment]
Thanks for the bug report -- this has now been fixed and deployed. The root cause of was that both sides of a trade are returned to the client to allow the client to choose which side to display. But the client didn't filter one side resulting in double counting.
