### ISSUE TITLE
Incorrect endpoint access

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#20]
User accounts with `ROLE_USER` access level are able to access information across different accounts/tenants. Below is a list of API endpoints where such authorisation flaws/breaches have occurred. I will add more to the list when I find them.

1. https://fm-data.herokuapp.com/api/approvals - lists approvals that shouldn't be visible by a normal user. It lists approvals across tenancies.
2. https://fm-data.herokuapp.com/api/approvals/{id} - this is perhaps cascaded from above
3. https://fm-data.herokuapp.com/api/approvals/{id}/account - similarly a likely cascade from above
4. https://fm-data.herokuapp.com/api/accounts/{id} - after following `_links` from number 3 above, `{"_links" : {"account" : {"href" : URL}}}` returns `Internal Server Error`
5. https://fm-data.herokuapp.com/api/accounts/{id}/owner - - after following `_links` from number 3 above, `{"_links" : {"owner" : {"href" : URL}}}` reveals cross-tenancy owner information
6. https://fm-data.herokuapp.com/api/users/{id} - reveals cross-tenancy user information
7. https://fm-data.herokuapp.com/api/users/{id}/account - reveals cross-tenancy user information
8. https://fm-data.herokuapp.com/api/accounts/{id}/marketplaces - reveals cross-tenancy user information and all embedded links are accessible
9. https://fm-data.herokuapp.com/api/marketplaces/{id}/currentHolding - reveals cross-tenancy data
10. https://fm-data.herokuapp.com/api/marketplaces/{id}/currentSession - reveals cross-tenancy data
11. https://fm-data.herokuapp.com/api/sessions/{id}/allocation
12. https://fm-data.herokuapp.com/api/allocations/{id}
13. https://fm-data.herokuapp.com/api/sessions/{id}/marketplace - and all the links embedded in the result
14. https://fm-data.herokuapp.com/api/funds - reveals cross-tenancy data and subsequent embedded links are also accessible.
15. https://fm-data.herokuapp.com/api/users - reveals all users in a given tenant account. This may or may not be desirable for `ROLE_USER` accounts.
16. https://fm-data.herokuapp.com/api/traders - same as /users endpoint. The output data for `ROLE_USER` may or may not be desirable. Subsequent links show more information than what should be permitted to `ROLE_USER`

**Comment by darkfishy** [comment]
Another endpoint:

17. https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={}

**Comment by darkfishy** [comment]
Another endpoint:

18. https://fm-data.herokuapp.com/api/markets - Cross-tenancy access
![image](https://user-images.githubusercontent.com/19355157/58855212-d6716f80-86e2-11e9-84a6-5a8b64eaef85.png)

**Comment by JanStureNielsen** [comment]
Internal tracking issue created -- closing this public issue.
