### ISSUE TITLE
Internal Server Error via API on Available Orders Search in a New and Empty MP/Market

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#23]
Steps to reproduce:
1. Create a new marketplace with one market
2. Do not open the marketplace yet
3. `GET` the `URL('https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}')` where `market_id` is for the market created above.

Response received: 
```
{
  "status" : "INTERNAL_SERVER_ERROR",
  "error" : "SERVER_ERROR",
  "message" : "Snap! :o"
}
```

Expected response:
```
{
  "_embedded": {
    "orders": []
  },
  "_links": {
    "self": {
      "href": "https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}&page=0&size=1000"
    }
  },
  "page": {
    "size": 1000,
    "totalElements": 0,
    "totalPages": 1,
    "number": 0
  }
}
```

**Comment by darkfishy** [comment]
The above error happens even if the marketplace is open, but the orderbook is empty.

**Comment by JanStureNielsen** [comment]
I'm not able to reproduce this, @darkfishy, on AHM -- would you try? If you're able to reproduce, add the curl command to the issue and re-open.

**Comment by darkfishy** [comment]
@JanStureNielsen Yes, this is not happening anymore. Though on the day I reported it, it happened more than once. Can't reproduce this anymore. Though it sill has the issue related to #25

**Comment by JanStureNielsen** [comment]
I can now duplicate this issue in a new marketplace in INIT state.

**Comment by JanStureNielsen** [comment]
Fix is now deployed to production.
