### ISSUE TITLE
Self-crossing trade affects holdings and history

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#24]
Steps to reproduce:
1. Create a new marketplace with a single market
2. Open the market
3. Submit a `SELL` order
4. Submit a matching `BUY` order
5. The self-trade takes place
6. Available `cash` and `units` change

Expected behaviour:
1. The above trade should not take place. Instead the two orders should cancel each other, effectively cancelling the order submitted first.

**Comment by darkfishy** [comment]
Visual trace:

Current State
![image](https://user-images.githubusercontent.com/19355157/43753858-25b6108a-9a4b-11e8-8ac6-f04ddb1bce74.png)

Submit `SELL` order
![image](https://user-images.githubusercontent.com/19355157/43753898-4f5dd008-9a4b-11e8-911e-ae8bfe43e837.png)

Submit `BUY` order of same unit/price combination
![image](https://user-images.githubusercontent.com/19355157/43753911-632dc5ca-9a4b-11e8-9c87-65327627493f.png)

Trade takes place and Available cash and units change
![image](https://user-images.githubusercontent.com/19355157/43753926-8028b66c-9a4b-11e8-8c67-50a8aad6a220.png)

**Comment by JanStureNielsen** [comment]
Thanks for the great bug report, @darkfishy -- this is now fixed and deployed.
