### ISSUE TITLE
No _embedded with zero resources

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#25]
Steps to reproduce:

1. Create a new marketplace with one market
2. Open the marketplace
3. Execute at least one trade in a way that there are no pending orders
  a. Send a `SELL` order
  b. Send an equivalent `BUY` order
  c. Trade takes place
4. `GET` the URL('https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}') where `market_id` is for the market created above.

Response received: 
```
{
  "_links" : {
    "self" : {
      "href" : "https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}&page=0&size=1000"
    }
  },
  "page" : {
    "size" : 1000,
    "totalElements" : 0,
    "totalPages" : 0,
    "number" : 0
  }
}
```

Expected response:
```
{
  "_embedded": {
    "orders": []
  },
  "_links": {
    "self": {
      "href": "https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}&page=0&size=1000"
    }
  },
  "page": {
    "size": 1000,
    "totalElements": 0,
    "totalPages": 1,
    "number": 0
  }
}
```

**Comment by darkfishy** [comment]
Similarly, it happens on following endpoint. `GET https://fm-data.herokuapp.com/api/marketplaces/`.

Seems to be a case where container is empty, the server isn't returning the `_embedded` object altogether.

**Comment by JanStureNielsen** [comment]
This is an artifact of the underlying REST HAL implementation which we cannot change so I will close this. In future, we may avoid this by using a different representation.
