### ISSUE TITLE
Don't write if password field is blank

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#27]
If the `password` field is empty for an existing user in users.csv, which was previously exported then edited, upon importing this CSV, password for those users gets deleted/set to empty.

This means that the user could not log in after that point. 

This is especially an issue for users with ROLE_MANAGER because if their password gets deleted, then that user cannot log back in.

Expected Behaviour:
If the password field is empty in imported CSV, then the password should not be changed.

**Comment by darkfishy** [comment]
Hey Jan. Has there been any progress on this? I also wouldn't classify this as an enhancement because I'd rather consider this bug, as it effectively locks out a manager account.

**Comment by JanStureNielsen** [comment]
Hi Abhi -- I'm working on account management features, including change of password; once this is complete the password field for the importer will be ignored.

**Comment by darkfishy** [comment]
Thanks Jan

**Comment by JanStureNielsen** [comment]
The import no longer sets null or empty passwords.
