### ISSUE TITLE
Different 401 responses

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#28]
For instance, upon trying to fetch marketplace info using the `/api/marketplaces/{id}`, the response for failed logins is inconsistent.

Sometimes the output is:
```
{
    'timestamp': '2018-08-17T03:12:32.964+0000', 
    'status': 401, 
    'error': 'Unauthorized', 
    'message': 'Full authentication is required to access this resource', 
    'path': '/api/marketplaces/{id}'
}
```

Whereas at other times it is just blank `'   '`. Sample output from FMClient is as below (timestamp in TZ Australia/Melbourne):
```
[2018-08-17 13:07:06,430:       comms.Request]:    ERROR - {'code': 401, 'response': {}}
```
Note that the `response` object above is just an empty string.

**Comment by JanStureNielsen** [comment]
I cannot reproduce this; for all endpoints I get, e.g.:
```
curl https://fm-data.herokuapp.com/api/users
{
  "timestamp" : "2019-01-24T20:30:40.661+0000",
  "status" : 401,
  "error" : "Unauthorized",
  "message" : "Full authentication is required to access this resource",
  "path" : "/api/users"
}
```
