### ISSUE TITLE
Mishandling of expired JWT tokens

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#29]
Currently, if a client tries to login using an expired token, the API server throws an `HTTP 500 Internal Server Error` with following headers and JSON response:

#### Headers:
```
Access-Control-Allow-Credentials: true
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Connection: keep-alive
Content-Type: application/json;charset=UTF-8
Expires: 0
Pragma: no-cache
Server: Cowboy
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Transfer-Encoding: chunked
Vary: Origin
Via: 1.1 vegur
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Xss-Protection: 1; mode=block
```
#### JSON Response:
```
{
    "timestamp" : "2018-08-29T00:29:04.323+0000",
    "status" : 500,
    "error" : "Internal Server Error",
    "exception" : "io.jsonwebtoken.ExpiredJwtException",
    "message" : "JWT expired at 2018-08-27T03:53:25Z. Current time: 2018-08-29T00:29:04Z, a difference of 160539321 milliseconds.  Allowed clock skew: 0 milliseconds.",
    "path" : "/api/marketplaces/"
}
```

I consider this counterintuitive from authorisation as well as system design perspective.

In case of authorisation failure, a client would normally expect `HTTP 401 Unauthorised`

Additionally, when a client requests authorisation token for the first time, using either `/api/tokens` or `/login` endpoints, perhaps a proper value for the `Expires` HTTP header, that corresponds to the time when a token would expire, must also be included.

Currently the server sends `Expires: 0`, which is also counterintuitive because as per `HTTP (RFC 2616 Sec 14)` that would mean that the resource has already expired; which is not true when logging in.

Given that the server also sends `'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate'`, which supersedes the `Expires` header in most clients and caches, this shouldn't change the semantics of these headers.

##### Questions:
1. Could the server be modified such that
  a. a `401 Unauthorised` error is thrown for expired JWTs
  b. upon successful login, the server also includes an appropriate value for `Expires` header
2. Are these changes feasible?

**Comment by JanStureNielsen** [comment]
This is now implemented.

2022-03-22 update: This should read "This is now implemented in FM-3".

**Comment by darkfishy** [comment]
Awesome. Thanks Jan. What does the server respond now in case of expired auth?

**Comment by JanStureNielsen** [comment]
Let's test this to make sure we are doing the right things at the right time.

**Comment by darkfishy** [comment]
I see that on [flexemarkets.com](https://guarded-ridge-89710.herokuapp.com/api/tokens) and [adhocmarkets.com](https://fm-data.herokuapp.com/api/tokens), returned headers on `/tokens` endpoint are still same as above. Especially in `Cache-Control: max-age` and `Expires` headers. Those values are still `0`.

**Comment by darkfishy** [comment]
I'll test what I get as response when using an expired token.

**Comment by darkfishy** [comment]
Hey @JanStureNielsen I tested this (expired token) and response is still a success `200 OK`, which isn't standards compliant. The response body is then empty, which also isn't helpful.

**Comment by JanStureNielsen** [comment]
Yes; this is clearly incorrect behavior. I'll take a look at this set of issues this week.

**Comment by darkfishy** [comment]
@JanStureNielsen Upon further investigation, this incorrect behaviour is present only in FM-2. Under **FM-3** it correctly returns `401 Unauthorized`. I am assuming that when you said

> This is now implemented

you meant FM-3 but not FM-2. Is that right?

**Comment by JanStureNielsen** [comment]
Correct -- only implemented in FM-3. I only back-port significant bugs with minimal stability risks to FM-2 but I should have made that clear in the comment above. I'll edit.

**Comment by darkfishy** [comment]
Thanks Jan. I suppose we can close this issue for now.

**Comment by darkfishy** [comment]
Oops. I shouldn't have been this hasty. There is still the issue of Headers `Expires: 0` and/or `Cache-Control: ...,max-age=0,...`
These should have a non-zero value as appropriate. Ideally, the value for `Expires` should be set for token validity and leave `Cache-Control` as-is because that is usually relevant for intermediate proxies.
Hence reopening.

**Comment by JanStureNielsen** [comment]
The `Expires` header was used HTTP/1.0 for client-side caching; however, it was shown to be difficult to implement correctly across clients and applications and as a result the use of the `Expires` header was deprecated in HTTP/1.1. With most traffic now being HTTP/1.1, the best practice for this header is to set the value to zero ("already expired").

Since the APIs set `Expires: 0` per best practices, I'm closing this issue. If you feel this is inappropriate, please open a new issue with additional details and I'll take another look.
