### ISSUE TITLE
Large holding values can visually overlap

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#30]
The UI has CSS issues with cash values overlapping when the values are large. See screenshot below:
![image](https://user-images.githubusercontent.com/19355157/44962760-f1eaf680-af67-11e8-94aa-2264beb40bb8.png)

Current screen resolution: 1080x1920
Current Viewport: 1079x1180

**Comment by JanStureNielsen** [comment]
I have opened an internal tracking issue on the general issue but I'm going to close this specific problem with large cash.
