### ISSUE TITLE
Show item name(s) when session is not open

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#31]
The names that are shown for Markets and Items are rather ambiguous depending upon the current state of the marketplace.

For instance, when the marketplace is `INIT/PAUSED/CLOSED`, only the `Market Name` and `Description` are shown.
![image](https://user-images.githubusercontent.com/19355157/44971477-0693b280-af99-11e8-971e-359f07aeb00f.png)

Whereas, when the marketplace is `OPEN`, the `Item Name` is shown. 
![image](https://user-images.githubusercontent.com/19355157/44971809-48712880-af9a-11e8-93c4-d7bbf0b95198.png)

Could the `Item Name` be shown as well when the MP is `not OPEN`?
This is useful when writing manager bots where reasoning is done on item name.

**Comment by JanStureNielsen** [comment]
This is resolved in FM-2.1 on flexemarkets.com:

![fm-issues-31](https://user-images.githubusercontent.com/4248566/69187866-9e1aed80-0ad8-11ea-9aae-31825afdaede.png)

**Comment by JanStureNielsen** [comment]
Closed in https://github.com/flexemarkets/fm-ui/pull/470/commits/a30b7e1c4469bb053de0562a82d5b660ce8bbb7a

![fm-issues-31](https://user-images.githubusercontent.com/4248566/69378728-32698980-0c6c-11ea-9b81-6cc08fe4b4f3.png)
