### ISSUE TITLE
Server Error 500 on Holdings CSV Import

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#32]
Holdings import with the new CSV structure throws Internal Server Error even with CSV that was just downloaded, sans trades.

CSV has following structure:

```
# holdings -- begin
account, email, owner, marketplace, session, name, cash, cash__initial, Gold_Bullion, Gold_Bullion__initial, Gold_Bullion__shorts, Gold_Bullion__buy, Gold_Bullion__sell
...
.
. Original data here
.
...
# holdings -- begin
```
Marketplace: 365
Session: 6883

Error thrown on the Web UI:
![image](https://user-images.githubusercontent.com/19355157/45276932-76a9b780-b508-11e8-84d1-f39d74acd355.png)

Tried uploading a few times and same error.

**Comment by darkfishy** [comment]
CSV file with TXT extension.
[datafile-365-6883-2018-09-10-12-49-09.csv.txt](https://github.com/flexemarkets/fm-issues/files/2365195/datafile-365-6883-2018-09-10-12-49-09.csv.txt)

**Comment by JanStureNielsen** [comment]
Hmm -- I wonder if (evil) MS Excel translated `true` and `false` to `TRUE` and `FALSE` -- would you down-case those and try? Obviously the parser should handle that but...

**Comment by darkfishy** [comment]
Yes, MS Excel was indeed changing capitalisation of `true` and `false` values to `TRUE` and `FALSE`. 
However, even when keeping the capitalisation of those values to lowercase, using vim, the holdings are not updated and server throws `Internal Server Error 500`

File attached here:
[datafile-365-6883-2018-09-10-15-41-59.csv.txt](https://github.com/flexemarkets/fm-issues/files/2365272/datafile-365-6883-2018-09-10-15-41-59.csv.txt)

**Comment by JanStureNielsen** [comment]
Importer fixed now.
