### ISSUE TITLE
Feature Request: Include owner ID in orders JSON

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#35]
Currently, the `order` JSON has following data fields:

```
{
  "createdDate" : "2019-06-19T04:42:11.197",
  "lastModifiedDate" : "2019-06-19T04:42:11.259",
  "id" : 2888693,
  "original" : 2888693,
  "supplier" : 2888693,
  "consumer" : null,
  "type" : "LIMIT",
  "side" : "BUY",
  "price" : 190,
  "units" : 1,
  "mine" : true,
  "marketplaceId" : 488,
  "marketId" : 892
}
```

In addition to the above, depending upon the endpoint used, the owner info is included only as a URL. This means that an additional network request has to be made to the server in order to get that information, which is also redundant.

It would be useful to have `owner_id` included as part of the `order` data structure. This `owner_id` would then correspond to the `id` of `user`s from the `/users` endpoint.

**Comment by JanStureNielsen** [comment]
This is now implemented. A "manager" will see `ownerId=<id>` in the REST APIs; and, "users" (i.e., non-managers) will see `ownerId=null` except for their own orders. The WS API includes `ownerId=null` except for their own orders for all roles at the moment; but the WS API will be updated to have similar functionality to the REST API for managers.
