### ISSUE TITLE
[BUG] Marketplace CSV Export contains HTML instead with Incorrect Data

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#41]
**Bug Description**
When exporting marketplaces list as CSV, on either FM or AHM, the exported data just contains HTML webpage instead of list of marketplaces with their respective structure (if that is the intention). It is possible that the export functionality was not intended to export the list of marketplaces and only holdings. Though I recall this working some long time ago.

It seems like the export function is looking for MP_ID, which is of course missing from the URL or request sent when clicking on Export.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://flexemarkets.com/accounts/<account-string\>/marketplaces'
2. Click on '3-vertical-dots menu > Export'
3. Click on Export button
4. Open the downloaded CSV file in any text editor

**Expected behaviour**
If the intention of export is only to export holdings, then this menu item should be either disabled or hidden while on marketplaces list view. However, ideally, this option should trigger a request to download list of marketplaces along with their settings (such as assets, allocations, etc).

**Screenshots**
Screenshots of steps taken and the exported CSV file
1. Menu > Export 
![image](https://user-images.githubusercontent.com/19355157/119915986-fde43580-bfa6-11eb-8301-78ed2ba64038.png)
2. Export Dialog on FM
![image](https://user-images.githubusercontent.com/19355157/119916099-397eff80-bfa7-11eb-80cc-f546e4ec3a7c.png)
3. Export Dialog on AHM
![image](https://user-images.githubusercontent.com/19355157/119917638-494c1300-bfaa-11eb-9f15-80d9d1660891.png)
4. CSV from FM
![image](https://user-images.githubusercontent.com/19355157/119916224-75b26000-bfa7-11eb-9b93-de839df664df.png)
5. CSV from AHM
![image](https://user-images.githubusercontent.com/19355157/119916251-8531a900-bfa7-11eb-8f20-9fc4601a6b79.png)

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.7
 - Browser: Google Chrome
 - Version: 90.0.4430.212 (Official Build) (x86_64)

**API Endpoint and Params**
As triggered by clicking on the Export button
 - URL: https://flexemarkets.com/accounts/path/to/marketplaces/export
 - Request Method: GET
 - Request Headers: 
accept: application/json, text/plain, \*/\*
content-disposition: attachment; filename=marketplaces.csv
content-type: application/csv
 - Request Payload: None

**Additional context**
Bug found by Rob Woods

**Comment by JanStureNielsen** [comment]
The bug is that the export & import options should not be present on the marketplace list view. The enhancement, as @darkfishy notes, could be to download one or more marketplace configurations. We'll fix the bug first, then add the long-awaited configuration export enhancement as a separate issue.

**Comment by darkfishy** [comment]
@JanStureNielsen Sounds good and just as I thought that the option wasn't meant to be there.

**Comment by JanStureNielsen** [comment]
This is now fixed in FM-3.
