### ISSUE TITLE
[FM-3] Microsecond resolution discrepancy between datetime fields in CSV and JSON

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#44]
Hey Jan(@JanStureNielsen),

There seems to be some discrepancy in the datetime fields that are returned in JSON (via REST/WS) compared to those via CSV.
In CSV, microsecond resolution is upto 6 digits, whereas in JSON it is upto 9. I already account for this in FM-Client, so this issue is more an RFC.

Is this by design?

Marketplace:
```json5
{
  account: 'lucid-try',
  mp_id: 1145,
  market: 2025,
  session: 41749, 
}
```

Order CSV:
```csv
account,email,owner,marketplace,session,market,target,order,original,supplier,consumer,type,side,units,price,createdDate,lastModifiedDate,clientDescription
lucid-try,abhijeet.anand@unimelb.edu.au,4689,1145,41749,2025,4730,25671470,25671470,25671470,NULL,LIMIT,BUY,1,10,2022-05-26T00:43:54.226540,2022-05-26T00:43:54.226540,fm-ui 3.1.1
```

Order JSON (from  trader's perspective)
```json5
{
    'id': 25671470,
    'original': 25671470,
    'supplier': 25671470,
    'consumer': null,
    'type': 'LIMIT',
    'side': 'BUY',
    'symbol': 'InsiderLow',
    'units': 1,
    'price': 10,
    'mine': false,
    'ownerId': 4689,
    'ownerTarget': 'T000',
    'accountId': 4688,
    'marketplaceId': 1145,
    'marketId': 2025,
    'sessionId': 41749,
    'clientDescription': null,
    'createdDate': '2022-05-26T00:43:54.226540431',
    'lastModifiedDate': '2022-05-26T00:43:54.226540431',
}
```

**Comment by JanStureNielsen** [comment]
The order CSV and JSON now have the same microsecond representation. Other objects still contain the default nanosecond resolution in JSON; these inconsistencies will be corrected with a custom serializer.

**Comment by darkfishy** [comment]
Thanks Jan. At this stage, Python FMClient does take it into account.
