### ISSUE TITLE
[FM-3] [BUG] Empty `ORDER-UPDATE` when private orders are sent/cancelled for non-self

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#46]
Hey Jan(@JanStureNielsen),

When private orders are sent/cancelled in a private market, a given trader receives empty list via `ORDER-UPDATE` WS sub, for orders that are not relevant to this trader.

Ideally, traders that are not party to a private order (as in owner and target), should not get any notification via `ORDER-UPDATE`.

@nitinef : What is your take? Is this relevant to you? I ask because you do want traders to be notified of empty order-book at start of connection or market open.

**Comment by JanStureNielsen** [comment]
In a private market, only the source and target should receive ORDER-UPDATE events on submit, cross, and cancel.

**Comment by darkfishy** [comment]
@JanStureNielsen That's indeed what I would expect, however, empty messages are still being sent to other traders. Below is an example for marketplace `1145`, market `2025` on order submission (`id: 25671483`):

```
MESSAGE
message-type:ORDERS-UPDATE
destination:/user/queue/marketplaces/1145
content-type:application/json
subscription:0
message-id:a84d7d78-2b87-9eb4-75e2-27a6954610f6-44
content-length:3

[ ]
```
And following for cancellation of the above order:
```
MESSAGE
message-type:ORDERS-UPDATE
destination:/user/queue/marketplaces/1145
content-type:application/json
subscription:0
message-id:a84d7d78-2b87-9eb4-75e2-27a6954610f6-47
content-length:3

[ ]
```

**Comment by darkfishy** [comment]
Also to add, it does make sense for an empty update for public (and/or private) markets at the start of sub, though not as an ongoing update.

**Comment by JanStureNielsen** [comment]
I favor never sending empty ORDER-UPDATE events over only sending empty ORDER-UPDATE events on subscribe. For my applications, this should be fine and I can't think of a scenario where this is inadequate. It's also cleaner to implement, of course.

Can you help clarify why an empty ORDER-UPDATE events on subscribe make sense, @darkfishy?

**Comment by darkfishy** [comment]
Hey @JanStureNielsen that question is best answered by @nitinef as this particular exception to the rule is his request.

**Comment by nitinef** [comment]
Hi @JanStureNielsen we need an update at the time of login. Just to point that current OB is empty when agent initialises.

**Comment by JanStureNielsen** [comment]
Hi @nitinef -- my applications initialize an empty order book and then update the state based on ORDER-UPDATE events so, they don't care when the "first" ORDER-UPDATE arrives. I'll refactor things a bit to see if I can implement a clean solution with a empty ORDER-UPDATE on subscribe but no empty ORDER-UPDATEs after that.

**Comment by darkfishy** [comment]
@nitinef Wouldn't it just be easier to assume that if there has been no update, the order book is empty? And at the time of starting a bot (irrespective of marketplace state) and at the time of marketplace open, agents can assume marketplace is empty and can also query our internal representation of the order book if required. I do agree with Jan, that we should not treat subscription event as special for empty orderbooks.

**Comment by darkfishy** [comment]
@nitinef In our case, I think the best place to do any initial check for empty order book would be at the time of session update. If, at the time of initialisation, the order book is not empty, then their logic would remain as is within the received orders method.

**Comment by darkfishy** [comment]
> it does make sense for an empty update for public (and/or private) markets at the start of sub

@JanStureNielsen Now I remember why I said this. 

If there is a proactive agent in a market, these agents may want to act as market maker. In which case they may want an authoritative answer at the start, on whether the order book is empty. If such an agent assumes that an order book is empty, it may lead to this agent sending incorrect orders or missing out sending initial orders (depending on agent's own logic of where to implement this behaviour). Does this make sense?

**Comment by JanStureNielsen** [comment]
Yeah -- slight penalty for this type of agent but it could wait to assess its state for some short time, say a second or two, and then act on empty if no ORDER-UPDATE.

**Comment by nitinef** [comment]
Hi @JanStureNielsen is it possible to get order update always when agent logs in (including empty order book). I think not having this will break a lot of our agents. The delay is not ideal I think in proactive bots. Moreover it’ll be cumbersome for students to include such functionality.

**Comment by JanStureNielsen** [comment]
Yes, no problem -- I've got it implemented but waiting on the fixes for the `ownerTarget` field in #45.

**Comment by JanStureNielsen** [comment]
Fix is now deployed to production.

**Comment by darkfishy** [comment]
Thanks Jan. I'll test it later tonight and let you know.

**Comment by JanStureNielsen** [comment]
Deployment of this fix seems to have triggered other bugs -- production reverted to prior version -- investigating.

**Comment by JanStureNielsen** [comment]
This is now fixed and validated in production.

**Comment by darkfishy** [comment]
Confirmed: No update on non-self private orders.
