### ISSUE TITLE
[FM-3] [BUG] Order cancellation sends original `LIMIT` order in `ORDERS-UPDATE`

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#48]
This is a new behaviour which wasn't present before today(!). This breaks existing robots.

Is there a reason for this change? Could this be reverted to its previous state, where only the `CANCEL` order was sent (at least that is how I recall it).

This bug could be related to #47

```json5
MESSAGE
message-type:ORDERS-UPDATE
destination:/user/queue/marketplaces/1145
content-type:application/json
subscription:sub-0
message-id:268522f6-fe6d-d09a-73d0-a686c34214af-43
content-length:985

[ {
  "createdDate" : "2022-05-30T11:17:08.28069924",
  "lastModifiedDate" : "2022-05-30T11:17:08.28069924",
  "id" : 25671492,
  "original" : 25671492,
  "supplier" : 25671492,
  "consumer" : 25671493,
  "type" : "LIMIT",
  "side" : "BUY",
  "symbol" : "OpenMarket",
  "units" : 1,
  "price" : 5,
  "mine" : true,
  "ownerId" : 4689,
  "ownerTarget" : null,
  "accountId" : 4688,
  "marketplaceId" : 1145,
  "marketId" : 2023,
  "sessionId" : 41749,
  "clientDescription" : "fm-ui 3.1.1"
}, {
  "createdDate" : "2022-05-30T11:24:09.767565545",
  "lastModifiedDate" : "2022-05-30T11:24:09.767565545",
  "id" : 25671493,
  "original" : 25671492,
  "supplier" : 25671493,
  "consumer" : 25671492,
  "type" : "CANCEL",
  "side" : "BUY",
  "symbol" : "OpenMarket",
  "units" : 1,
  "price" : 5,
  "mine" : true,
  "ownerId" : 4689,
  "ownerTarget" : null,
  "accountId" : 4688,
  "marketplaceId" : 1145,
  "marketId" : 2023,
  "sessionId" : 41749,
  "clientDescription" : "fm-ui 3.1.1"
} ]
```

**Comment by JanStureNielsen** [comment]
Production is now reverted to May 19 code-base -- investigating.

**Comment by JanStureNielsen** [comment]
This is now fixed and validated in production.

**Comment by JanStureNielsen** [comment]
This is not deployed, yet.

**Comment by JanStureNielsen** [comment]
The behavior in this scenario is the same in FM-3 as it is in FM-2 for both private and public markets. I'm going to close this since this is "as-designed". If you feel this is incorrect, i.e., we should have different behavior from FM-2, please re-open with the details.

**Comment by darkfishy** [comment]
Hey Jan. I am a bit confused. Could you explain the 'as-designed' behaviour? Is it that on cancelling an order, both the new `CANCEL` and the original `LIMIT` orders are sent as part of an update?

**Comment by JanStureNielsen** [comment]
That's correct, @darkfishy: on cancel, both the original LIMIT order and the CANCEL order are sent to both parties. Once cancelled, subsequent subscription ORDERS-UPDATE won't include the pair. This behavior is what FM-2 does. If FM-3 behaves differently, that is a bug in FM-3.
