### ISSUE TITLE
[FM-3] [BUG] CORS error when making API request from browser (AlgoHost)

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#49]
**Bug Description**
API requests fail when trying to access resources on server, such as the one below.

**To Reproduce**
Make a request to `FM-3` server from `algohost.bmmlab.org` or `localhost` via browser (using JWT; authentication is done on algohost server, instead of browser). See error below:
```
Access to XMLHttpRequest at 'https://fm-data.herokuapp.com/api/marketplaces/?size=100' from origin 'http://127.0.0.1:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Access to XMLHttpRequest at 'https://fm-data.herokuapp.com/api/marketplaces/?size=100' from origin 'https://algohost.bmmlab.org' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
This is possibly due to `Referrer Policy: strict-origin-when-cross-origin`.

**Expected behaviour**
API requests from browser from hosts (algohost.bmmlab.org or localhost) is allowed.

Could you add the above two hosts to FM-3 allowed_hosts?

**Comment by JanStureNielsen** [comment]
Added the below hosts to CORS configuration:
```
http://127.0.0.1:8000
https://algohost.bmmlab.org
```

**Comment by darkfishy** [comment]
Thanks Jan. Confirmed that it works.
