### ISSUE TITLE
Can't submit order with price at $0.00

### ISSUE THREAD

**Issue by ywhcuhk** [flexemarkets/fm-issues#5]
The system will reject the order when buying or selling at the price of $0. This is not necessarily wrong or a bug. But in some occasions, we ask the participants to submit at $0 if they are not willing to pay for something just to fill the data point. 

We can always set the minimum tick at 1 cent if we don't want to have $0 price. So I think with $0 allowed, there is more flexibility.

**Comment by JanStureNielsen** [comment]
Good point, @ywhuofu -- any concerns with this @asparouhova and @pbossaerts?

**Comment by JanStureNielsen** [comment]
You can now submit orders at or above the minimum price specified in the market, including zero.
