### ISSUE TITLE
Missing currentSession and currentHolding on /marketplace/{id}

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#6]
The response on querying a `/marketplace/{id}` is missing `currentSession` and `currentHolding`.

**Comment by JanStureNielsen** [comment]
What's the complete URL, @nitinef? Do you know about when this started failing?

**Comment by nitinef** [comment]
I am querying https://guarded-ridge-89710.herokuapp.com/api/marketplaces/33. It was working fine 8 hours ago.

**Comment by JanStureNielsen** [comment]
Back-end now fixed to address this.
