### ISSUE TITLE
Missing ordersAvailable and ordersCompleted on /markets/{id}

### ISSUE THREAD

**Issue by nitinef** [flexemarkets/fm-issues#7]
On querying market url (e.g., https://guarded-ridge-89710.herokuapp.com/api/markets/58), the key-value pairs for `ordersAvailable` and `ordersCompleted` are no longer available under `_links`.

**Comment by JanStureNielsen** [comment]
https://guarded-ridge-89710.herokuapp.com/api/marketplaces
